language: python
python:
  - "2.7"
  - "3.5"
env:
  - MPLBACKEND=Agg
# Command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
# Command to run tests
script:
  - cd tests
  - pytest -v